import { useSelector } from 'react-redux'
import { selectInit } from '../features/init/initSlice'

export const useLang = () => {
  const { initData } = useSelector(selectInit)

  const messages = {
    ...initData.messages,
    form_error_email: "Некорректный e-mail",
    form_error_required: "Обязательное поле",
    form_error_format: 'Неверный формат',
    form_error_min_length: 'Минимум :num символов',
    form_error_max_value: 'Максимальное значение :num',
    form_error_equal: 'Не совпадает с предыдущим значением',
    form_error_number: 'Некорректное число',
    ts_back: "Назад",
    ts_login_header: "Авторизация",
    ts_login_title: "Войдите в аккаунт",
    ts_login_description: "Чтобы использовать все возможности",
    ts_login_email_title: 'Войдите или создайте аккаунт',
    ts_login_email_label: 'Адрес электронной почты',
    ts_login_email_btn: 'Продолжить',
    ts_login_footer: 'Входя в аккаунт или создавая новый, вы соглашаетесь с нашими <a href="/info/rule" target="_blank">Правилами и условиями</a> и <a href="/info/privacy-policy" target="_blank">Положением о конфиденциальности</a>',
    ts_login_name_lead: 'Мы рады, что вы решили зарегистрироваться.<br> Укажите ваши данные.',
    ts_login_name_label: 'Имя',
    ts_login_surname_label: 'Фамилия',
    ts_login_phone_title: 'Укажите номер телефона',
    ts_login_phone_lead: 'Он будет использоваться только в редких случаях, когда объекту размещения понадобится с вами связаться.',
    ts_login_phone_label: 'Ваш номер телефона',
    ts_login_create_password_title: 'Создание пароля',
    ts_login_create_password_lead: 'Пароль должен состоять из заглавных и строчных букв и цифр. Длина — не менее 6 символов.',
    ts_login_create_password_label: 'Пароль',
    ts_login_create_repassword_label: 'Введите пароль еще раз',
    ts_login_create_password_btn: 'Создать аккаунт',
    ts_registration_header: "Регистрация",
    ts_login_finish_title: 'Почти готово!',
    ts_login_finish_lead: 'Просто проверьте свою электронную почту и подтвердите данные. После этого вы сможете управлять всеми своими бронированиями из одного аккаунта.',
    ts_login_finish_btn: 'ОК',
    ts_login_password_title: 'Введите пароль',
    ts_login_password_label: 'Пароль',
    ts_login_password_reset_btn: 'Забыли пароль?',
    ts_login_password_btn: 'Войти',
    ts_login_reset_password_email_title: 'Восстановление пароля',
    ts_login_reset_password_email_lead: 'Введите адрес вашей электронной почты для восстановления пароля.',
    ts_login_reset_password_email_btn: 'Отправить',
    ts_login_reset_password_title: 'Новый пароль',
    ts_login_reset_password_lead: 'Код для восстановления пароля отправлен на email',
    ts_login_reset_password_code_label: 'Введите код с письма',
    ts_login_reset_password_btn: 'Отправить',
    ts_login_birthday_label: 'Дата рождения',
    ts_login_gender_label: 'Пол',
    ts_gender_male: 'Мужской',
    ts_gender_female: 'Женский',
    ts_save: 'Сохранить',
    ts_points_available: 'Доступно баллов:',
    ts_profile: 'Профиль',
    ts_profile_nav_data: 'Посмотреть профиль',
    ts_profile_nav_loyalty: 'Программа лояльности',
    ts_profile_nav_history: 'Мои заказы',
    ts_profile_nav_logout: 'Выйти',
    ts_profile_edit_success_title: 'Готово',
    ts_profile_edit_success_text: 'Ваши данные успешно обновлены.',
    ts_nothing_found: 'Ничего не найдено',
    ts_loyalty_programm: 'Программа лояльности',
    ts_loyalty_status: 'уровень',
    ts_loyalty_balance: 'Текущий баланс:',
    ts_order_from: 'Заказ от',
    ts_load_more_booking: 'Посмотреть больше заказов',
    ts_write_bonuses: 'Списать бонусы:',
    ts_accrue_bonuses: 'Начислим бонусы',
  }

  return (text) => (messages[text] ? messages[text] : '!__' + text + '__!')
}